AWSTemplateFormatVersion: "2010-09-09"

Parameters:
    Environment:
        Description: Environment ID
        Type: String

Resources:
    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Sub "scc-app-${AWS::Region}-${AWS::AccountId}-${Environment}"
            WebsiteConfiguration:
                IndexDocument: index.html
            PublicAccessBlockConfiguration:
                BlockPublicPolicy: false

    S3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Sid: "PublicReadGetObject"
                      Effect: Allow
                      Principal: "*"
                      Action: "s3:GetObject"
                      Resource: !Sub "${S3Bucket.Arn}/*"

Outputs:
    BucketName:
        Description: The name of the S3 bucket
        Value: !Ref S3Bucket
    WebsiteURL:
        Description: "URL of the static website"
        Value: !GetAtt S3Bucket.WebsiteURL
