- name: Deploy application
  hosts: localhost
  gather_facts: false
  vars:
      temp: "{{ lookup('env', 'RUNNER_TEMP') }}"
  tasks:
      - debug:
            msg: "Installing version {{ version }} on {{ enviro_name }}"

      - name: Download archive
        ansible.builtin.get_url:
            url: "https://github.com/pezzu/scc-app/releases/download/{{version}}/public.zip"
            dest: "{{ temp }}"
            mode: "u=rw,g=r,o=r"
        register: downloaded

      - name: Unpack archive
        ansible.builtin.unarchive:
            src: "{{ downloaded.dest }}"
            dest: "{{ temp }}"
            list_files: true
            remote_src: true
        register: extracted

      - name: Get stats
        ansible.builtin.stat:
            path: "{{ extracted.dest }}/{{ item }}"
        loop: "{{ extracted.files }}"
        register: files_stats

      - name: Filter directories
        ansible.builtin.set_fact:
            files_only: "{{ files_only | default([]) + [item.item] }}"
        loop: "{{ files_stats.results }}"
        when: item.stat.isreg

      - name: Upload files
        amazon.aws.aws_s3:
            bucket: "scc-app-us-east-1-127141178998-{{enviro_name}}"
            object: "{{ item }}"
            src: "{{ extracted.dest }}/{{ item }}"
            mode: put
        loop: "{{ files_only }}"
        register: upload_results
