name: Destroy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to destroy"
                required: true
                default: "QA92-05"

jobs:
    destroy:
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1

        runs-on: ubuntu-latest
        steps:
            - name: lowercase Environment
              run: |
                  echo "environment=${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]' >> "${GITHUB_ENV}"

            - name: Destroy Infrastructure
              run: |
                  aws s3 rm s3://scc-app-us-east-1-127141178998-${environment} --recursive
                  aws cloudformation delete-stack --stack-name scc-app-cloudformation-stack-${environment}
